{{- if .Values.chaosServer.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chaos-mesh.name" . }}-chaos-server
  labels:
    app.kubernetes.io/name: {{ template "chaos-mesh.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: chaos-server
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
data:
  {{/*
     Rather than maintain a comprehensive ConfigMap, we map all sub-keys of the "env" value here.
     This allows for more flexibility and less Chart churn as Chaos Server evolves.
    */}}
  {{- range $envKey, $envVal := .Values.chaosServer.env }}
  {{ $envKey | upper }}: {{ $envVal | quote }}
  {{- end }}
{{- end }}
