{{- if .Values.chaosServer.create }}
{{- if .Values.chaosServer.persistentVolume.enabled -}}
{{- if not .Values.chaosServer.persistentVolume.existingClaim -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "chaos-mesh.name" . }}-chaos-server
  labels:
    app.kubernetes.io/name: {{ template "chaos-mesh.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: chaos-server
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
{{- if .Values.chaosServer.persistentVolume.storageClass }}
{{- if (eq "-" .Values.chaosServer.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.chaosServer.persistentVolume.storageClass }}"
{{- end }}
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.chaosServer.persistentVolume.size }}"
{{- end -}}
{{- end -}}
{{- end -}}
