apiVersion: v1
kind: Service
metadata:
  name: chaos-mesh-controller-manager
  labels:
    app.kubernetes.io/name: {{ template "chaos-mesh.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: controller-manager
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  type: {{ .Values.controllerManager.service.type }}
  ports:
    - port: 10080
      targetPort: http
      protocol: TCP
      name: http
    - port: 443
      targetPort: webhook
      protocol: TCP
      name: webhook
  selector:
    app.kubernetes.io/component: controller-manager
    app.kubernetes.io/instance: {{ .Release.Name }}
