apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-example
  namespace: chaos-testing
spec:
  action: pod-failure
  mode: all
  value: ""
  duration: "9m"
  selector:
    labelSelectors:
      "app.kubernetes.io/component": "chaos-daemon"
  scheduler:
    cron: "@every 10m"
