---
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: chaos-testing
  labels:
    app: busybox
spec:
  containers:
    - image: busybox
      name: busybox
      command: ["ping","localhost"]
