---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaosfs-etcd
  namespace: chaos-testing
  labels:
    app.kubernetes.io/component: webhook
data:
  chaosfs-etcd: |
    name: chaosfs-etcd
    selector:
      labelSelectors:
        app: etcd
    template: chaosfs-sidecar
    arguments:
      ContainerName: "etcd"
      DataPath: "/var/run/etcd/default.etcd"
      MountPath: "/var/run/etcd"
      VolumeName: "datadir"
