apiVersion: chaos-mesh.org/v1alpha1
kind: IoChaos
metadata:
  name: io-delay-example
  namespace: chaos-testing
spec:
  action: delay
  mode: one
  duration: "400s"
  path: ""
  selector:
    labelSelectors:
      "app.kubernetes.io/component": "tikv"
  layer: "fs"
  delay: "10ms"
  scheduler:
    cron: "@every 10m"
