apiVersion: pingcap.com/v1alpha1
kind: IoChaos
metadata:
  name: io-errno-example
  namespace: chaos-testing
spec:
  action: errno
  mode: one
  duration: "400s"
  configName: "chaosfs-tikv"
  path: ""
  selector:
    labelSelectors:
      "app.kubernetes.io/component": "tikv"
  layer: "fs"
  percent: "50"
  scheduler:
    cron: "@every 10m"
