---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chaosfs-tiflash
  namespace: chaos-testing
  labels:
    app.kubernetes.io/component: webhook
data:
  chaosfs-tiflash: |
    name: chaosfs-tiflash
    selector:
      labelSelectors:
        "app.kubernetes.io/component": "tiflash"
    template: chaosfs-sidecar
    arguments:
      ContainerName: "pd"
      DataPath: "/data/db"
      MountPath: "/data"
      VolumeName: "data"
