name: Upload chaos mesh crd
on:
  push:
    branches:
      - master
    paths:
      - install.sh
      - manifests/crd.yaml
      - manifests/chaosfs-sidecar.yaml
      - examples/web-show/deploy.sh
jobs:
  run:
    name: Upload crd file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          # Must use at least depth 2!
          fetch-depth: 2
      - name: Configure awscli
        run: |
          pip3 install --upgrade setuptools
          pip3 install awscli
          printf "%s\n" ${{ secrets.AWS_ACCESS_KEY }} ${{ secrets.AWS_SECRET_KEY }} ${{ secrets.AWS_REGION }} "json" | aws configure
      - name: Upload crd file
        run: |
          GIT_TAG=${GITHUB_REF##*/}
          if [[ "$GIT_TAG" == "master" ]]; then
            GIT_TAG="latest"
          fi
          aws s3 cp install.sh ${{ secrets.AWS_BUCKET_NAME }}/${GIT_TAG}/install.sh
          aws s3 cp manifests/crd.yaml ${{ secrets.AWS_BUCKET_NAME }}/${GIT_TAG}/crd.yaml
          aws s3 cp examples/web-show/deploy.sh ${{ secrets.AWS_BUCKET_NAME }}/${GIT_TAG}/web-show/deploy.sh
          # TODO: delete it
          aws s3 cp manifests/chaosfs-sidecar.yaml ${{ secrets.AWS_BUCKET_NAME }}/${GIT_TAG}/chaosfs-sidecar.yaml
