name: Website Deployment

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/website.yml
      - website/**

jobs:
  deploy-website:
    name: Deplpy website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Cache/restore dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ./website/node_modules
          key: website-${{ hashFiles('website/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --cwd ./website

      - name: Add key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT

      - name: Release to GitHub Pages
        working-directory: ./website
        env:
          USE_SSH: true
          GIT_USER: git
          NAME: ${{ secrets.GH_PAGES_DEPLOY_NAME }}
          EMAIL: ${{ secrets.GH_PAGES_DEPLOY_EMAIL }}
        run: |
          git config --global user.email "$EMAIL"
          git config --global user.name "$NAME"
          yarn deploy
